### ISSUE TITLE
Object [object Object] has no method 'getPropertySync'

### ISSUE THREAD

**Issue by jmatsushita** [inolen/titan-node#10]
Hi there,

I did the following on OSX with npm v1.4.14. 

```
npm install titan-node
```

It built successfully.

I then created an `index.js` file with the example code in the Readme. Then

```
node index.js
```

Asked me to install Java SE 6 (accepted). Reran (added the `DEBUG` log level, and the following error came up.

```
11:12:04.659 [main] DEBUG c.t.t.d.k.CachedKeyColumnValueStore - Cache Retrieval on edgestore. Attempts: 47 | Misses: 47
11:12:04.661 [main] DEBUG c.t.t.g.database.StandardTitanGraph - Saving transaction. Added 59, removed 0
11:12:04.737 [main] DEBUG c.t.t.g.b.TitanBlueprintsGraph - Committed thread-bound transaction standardtitantx[null]
11:12:04.778 [Thread-5] DEBUG c.t.t.d.k.CachedKeyColumnValueStore - Cache Retrieval on vertexindex. Attempts: 48 | Misses: 48
11:12:04.778 [Thread-5] DEBUG c.t.t.d.k.CachedKeyColumnValueStore - Cache Retrieval on edgestore. Attempts: 49 | Misses: 49
11:12:04.779 [Thread-5] DEBUG c.t.t.d.k.CachedKeyColumnValueStore - Cache Retrieval on edgestore. Attempts: 50 | Misses: 49
11:12:04.785 [Thread-6] DEBUG c.t.t.d.k.CachedKeyColumnValueStore - Cache Retrieval on vertexindex. Attempts: 51 | Misses: 49
11:12:04.786 [Thread-6] DEBUG c.t.t.d.k.CachedKeyColumnValueStore - Cache Retrieval on edgestore. Attempts: 52 | Misses: 50
11:12:04.786 [Thread-6] DEBUG c.t.t.d.k.CachedKeyColumnValueStore - Cache Retrieval on edgestore. Attempts: 53 | Misses: 50

/Users/jun/dev/uf6/titan-node/index.js:11
    var name = grandchild.getPropertySync('name');
                          ^
TypeError: Object [object Object] has no method 'getPropertySync'
    at /Users/jun/dev/uf6/titan-node/index.js:11:27
    at /Users/jun/dev/uf6/titan-node/node_modules/titan-node/node_modules/gremlin/lib/pipeline-wrapper.js:464:5
```

**Comment by htaox** [comment]
try:

``` js
grandchild.getProperty('name', function(err, name){
  console.log(name);
});
```

The above is from the author's [test file](https://github.com/inolen/gremlin-node/blob/master/test/test-graph-wrapper.js)

**Comment by inolen** [comment]
Right, I think this is just an out of date README. IIRC, I completely removed the majority of the *Sync methods.
